// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import tailwind from '@astrojs/tailwind';

// Single source of truth: `base` below and every redirect target derive from this.
// Astro applies `base` to links it generates, but NOT to `redirects` targets - a
// target written as `/guidelines/...` resolves to unional.github.io/guidelines/...
// and 404s. Verified against the built output.
const base = 'typescript-blackbook';
/** @param {string} path */
const to = (path) => `/${base}${path}`;

// https://astro.build/config
export default defineConfig({
	// Every URL the live Docusaurus site serves today, mapped to its Starlight
	// equivalent. Taken from the built `gh-pages` branch rather than inferred from
	// filenames - several live slugs come from frontmatter and do not match their
	// file (`naming-convention` is singular, `package-json` was already kebab).
	//
	// Docusaurus served docs under `/docs` and posts under `/blog`; Starlight serves
	// docs at the root and posts under `/blogs`, so every existing link breaks
	// without these.
	redirects: {
		// Docs landing pages.
		'/docs': to('/'),
		'/docs/guidelines': to('/guidelines'),
		// Doc pages, one for one.
		'/docs/guidelines/documentations/comments': to('/guidelines/documentations/comments'),
		'/docs/guidelines/files_and_folders/naming-convention': to('/guidelines/files-and-folders/naming-conventions'),
		'/docs/guidelines/project/npmignore': to('/guidelines/project/npmignore'),
		'/docs/guidelines/project/package-json': to('/guidelines/project/package-json'),
		'/docs/guidelines/project/package_name': to('/guidelines/project/package-name'),
		'/docs/tsconfig/declaration_map': to('/tsconfig/declaration-map'),
		'/docs/typescript_features/assertion_funtion': to('/typescript-features/assertion_funtion'),
		// Blog. Post slugs already match; only the `/blog` -> `/blogs` prefix moved.
		'/blog': to('/blogs'),
		'/blog/2022-eslint-plugin-peer-deps': to('/blogs/2022-eslint-plugin-peer-deps'),
		'/blog/2022-migrate-to-esm': to('/blogs/2022-migrate-to-esm'),
		'/blog/2022-tsc-esm-fix': to('/blogs/2022-tsc-esm-fix'),
		'/blog/2022-typescript-is-abstraction': to('/blogs/2022-typescript-is-abstraction'),
		'/blog/archive': to('/blogs'),
		// Docusaurus generated tag indexes. Starlight has no tag pages, so these
		// collapse to the nearest section rather than 404. If tags are wanted back,
		// these should point at real pages instead.
		'/blog/tags': to('/blogs'),
		'/blog/tags/eslint': to('/blogs'),
		'/blog/tags/esm': to('/blogs'),
		'/blog/tags/typescript': to('/blogs'),
		'/blog/tags/typescript-eslint': to('/blogs'),
		'/docs/tags': to('/'),
		'/docs/tags/comment': to('/'),
		'/docs/tags/documentation': to('/'),
		'/docs/tags/dx': to('/'),
		'/docs/tags/file': to('/'),
		'/docs/tags/folder': to('/'),
		'/docs/tags/naming': to('/'),
		'/docs/tags/project': to('/'),
		'/docs/tags/tsconfig': to('/'),
		'/docs/tags/type-plus': to('/'),
		'/docs/tags/typescript': to('/'),
		// Docusaurus scaffold demo page; no equivalent.
		'/markdown-page': to('/')
	},
    site: 'https://unional.github.io/',
    base,
    integrations: [starlight({
        title: 'TypeScript Blackbook',
        // Tailwind's base is loaded here rather than injected globally by
        // @astrojs/tailwind. Starlight's own styles sit in `@layer starlight.*`,
        // and unlayered CSS wins over layered CSS regardless of specificity, so a
        // global preflight overrode every Starlight rule - the header logo
        // rendered at its natural 512px and the hero button drew grey text on a
        // pale blue pill. See `applyBaseStyles: false` below.
        customCss: ['./src/tailwind.css'],
        favicon: './src/assets/logo.svg',
        logo: { src:'./src/assets/logo.svg'},
        social: [
            {
                label: 'X',
                icon: 'x.com',
                href: 'https://x.com/unional',
            },
            {
                label: 'Discord',
                icon: 'discord',
                href: 'https://discord.gg/RwzcFpN5fv',
            },
            {
                label: 'GitHub',
                icon: 'github',
                href: 'https://github.com/unional',
            },
            {
                label: 'Stack Overflow',
                icon: 'stackOverflow',
                href: 'https://stackoverflow.com/users/3505900/unional',
            },
            {
                label: 'YouTube',
                icon: 'youtube',
                href: 'https://www.youtube.com/@cyberuni',
            },
        ],
        // Autogenerated per top-level section rather than listed by hand: every
        // page under these directories appears automatically, so adding a doc
        // does not also require remembering to add it here. The previous config
        // listed a single entry, `guides/welcome`, which left all fourteen real
        // doc pages routable but absent from the navigation.
        sidebar: [
            { label: 'Guides', autogenerate: { directory: 'guides' } },
            { label: 'Guidelines', autogenerate: { directory: 'guidelines' } },
            { label: 'tsconfig', autogenerate: { directory: 'tsconfig' } },
            { label: 'TypeScript Features', autogenerate: { directory: 'typescript-features' } },
            { label: 'Tips', autogenerate: { directory: 'tips' } },
        ],
		}), tailwind({ applyBaseStyles: false })]
});